# -*- coding: utf-8 -*-
"""Regression Models and Performance Metrics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10ebYznIbHrN1EXjRjfSrWVZ50hrL3rzj
"""

'''Question 1 : What is Simple Linear Regression (SLR)? Explain its purpose.
   answwer:
   Simple Linear Regression (SLR) is a statistical and machine-learning technique used to model the relationship
   between one independent variable (X) and one dependent variable (Y) by fitting a straight line to the data.

          Purpose of Simple Linear Regression

Understand Relationships
To determine how changes in one variable affect another (e.g., how study hours affect exam scores).

Prediction
To predict the value of the dependent variable for a given value of the independent variable.

Quantify Impact
To measure the strength and direction (positive or negative) of the relationship using the slope.

Question 2: What are the key assumptions of Simple Linear Regression?
Answer:
Key Assumptions of Simple Linear Regression (SLR):

Linearity
There is a linear relationship between the independent variable (X) and the dependent variable (Y).

Independence of Errors
The residuals (errors) are independent of each other (no autocorrelation).

Homoscedasticity
The variance of the residuals is constant across all values of X.

Normality of Errors
The residuals are normally distributed (mainly required for hypothesis testing and confidence intervals).

No or Little Multicollinearity
Since SLR has only one independent variable, multicollinearity is not an issue (this assumption matters more in multiple regression).

Question 3: Write the mathematical equation for a simple linear regression model and
explain each term.
Answer:Mathematical Equation of Simple Linear Regression (SLR):

Y=β0+β1X+ε

Y – Dependent variable (Response)
The variable we want to predict or explain.

𝑋
X – Independent variable (Predictor)
The variable used to explain or predict
𝑌
Y.

𝛽
0
β
0
	​

 – Intercept
The expected value of
𝑌
Y when
𝑋
=
0
X=0. It represents where the regression line crosses the Y-axis.

𝛽
1
β
1
	​

 – Slope (Regression coefficient)
The change in
𝑌
Y for a one-unit increase in
𝑋
X. It shows the direction and strength of the relationship.

𝜀
ε – Error term (Residual)

Question 4: Provide a real-world example where simple linear regression can be
applied.
Answer:A clear real-world example of Simple Linear Regression (SLR) is:

 House Rent vs Size of the House

Scenario:
Suppose you want to predict the monthly rent of a house based on its size (in square feet).

Independent variable (X): Size of the house (sq. ft.)

Dependent variable (Y): Monthly rent (₹)

Question 5: What is the method of least squares in linear regression?
Answer:The method of least squares is a statistical technique used to estimate the parameters
of a linear regression model. Its objective is to find the best-fit regression line by minimizing the sum of the squares of the residuals (errors).

Residual (error):
The difference between the observed value and the predicted value of the dependent variable.

Question 6: What is Logistic Regression? How does it differ from Linear Regression?
Answer:Logistic Regression is a statistical and machine learning technique used for classification problems,
especially when the dependent variable is binary (e.g., Yes/No, 0/1, Pass/Fail).
Instead of predicting a continuous value, it predicts the probability that an observation belongs to a particular class.
linear Regression: Predicting exam marks based on hours studied
Logistic Regression: Predicting whether a student will pass or fail based on hours studied

Question 7: Name and briefly describe three common evaluation metrics for regression
models.
Answer:Three Common Evaluation Metrics for Regression Models

Mean Absolute Error (MAE)
MAE measures the average absolute difference between the actual values and the predicted values.

Easy to understand and interpret

Treats all errors equally

Mean Squared Error (MSE)
MSE measures the average of the squared differences between actual and predicted values.

Penalizes larger errors more heavily

Useful when large errors are especially undesirable

Root Mean Squared Error (RMSE)
RMSE is the square root of MSE, bringing the error back to the original unit of the target variable.


More interpretable than MSE

Sensitive to outliers

In short:

MAE → average size of errors

MSE → emphasizes large errors

RMSE → standard deviation of prediction errors

Question 8: What is the purpose of the R-squared metric in regression analysis?
Answer:R-squared (R²) is a statistical measure used to evaluate how well a regression model explains the variability of the dependent variable.

Purpose:

It indicates the proportion of variance in the dependent variable that is explained by the independent variable(s).

It helps assess the goodness of fit of a regression model.

'''Question 9: Write Python code to fit a simple linear regression model using scikit-learn
and print the slope and intercept.'''
import numpy as np
from sklearn.linear_model import LinearRegression

# Sample data
X = np.array([1, 2, 3, 4, 5]).reshape(-1, 1)  # Independent variable
y = np.array([2, 4, 6, 8, 10])              # Dependent variable

# Create and train the model
model = LinearRegression()
model.fit(X, y)

# Print slope and intercept
print("Slope (Coefficient):", model.coef_[0])
print("Intercept:", model.intercept_)

'''Question 10: How do you interpret the coefficients in a simple linear regression model?
Answer:In a simple Linear regression ,y=b0+b1x+e, the slope and intercept have the following interpretations:
Intercept
The intercept b0 is predicted value of y when x=0. It represents where the regression line crosses the y-axis.

Slope
The slope b1 represents the change in the predicted value of y for a one-unit change in x.'''